### ISSUE TITLE
Thank You For Making This!

### ISSUE THREAD

**Issue by kiprasvitas** [rsanjuan87/PsiphonQt#11]
Hello! I just wanted to say thank you for making this repository as it immediately solves my issue of having a working Psiphon version for MacOS! Thank you so much for your contribution to GitHub!

**Comment by reyespinosa1996** [comment]
@Kzapas Thank you for using it. We (the community) hope it work for you and to avoid censorship and discrimination. Think about give the project a star and don't hesitate to spread the word.
