### ISSUE TITLE
Devolver estados de proxy

### ISSUE THREAD

**Issue by rsanjuan87** [rsanjuan87/PsiphonQt#3]
Si se cae la conexión a internet mientras usas PsiphonQt pasa el problema q le dio al amigo 
No elimina los proxis al cerrar el app
https://t.me/RailabMac/36525

**Comment by cuza97** [comment]
la cosa es que cuando le das en cerrar sin antes no desactivar el psiphonqt no te restablece la configuración del proxy

**Comment by rsanjuan87** [comment]
listo detectado y corregido
https://github.com/rsanjuan87/PsiphonQt/commit/961c35675823dd190551d2b364d100cd31b770f1

**Comment by cuza97** [comment]
@cuza97 que bueno
