### ISSUE TITLE
It dosen't connect on linux Mint 20.20 ( base Ubuntu 20.04)

### ISSUE THREAD

**Issue by daguitosama** [rsanjuan87/PsiphonQt#4]
I have downloaded the tar and runned the app using bash. The apps runs ok every thing in the Ui works but, once i click connect the button turns green but it never change the cuban IP. I have used a mobile data network of an iPhone.

**Comment by rsanjuan87** [comment]
remember if you are using Firefox or another browser or app set it to take the system proxy or manually configure it to 127.0.0.1:8081 or the port you have configured

**Comment by daguitosama** [comment]
Ahh that make sense, but there is a way to route  the entire traffic, not just the browser with a proxy, the hole traffic of the system as an usual VPN ?

Sent with 💚 from havana

**Comment by rsanjuan87** [comment]
Bueno esto debe ponerte en tus ajustes de proxy del sistema el q el psiphon está generando, por defecto es 127.0.0.1:8081
Verificar eso, además de q las variables de entorno http_proxy y https_proxy estén a la configuración

> Ahh that make sense, but there is a way to route the entire traffic, not just the browser with a proxy, the hole traffic of the system as an usual VPN ? Sent with 💚 from havana
> […](#)
> On Jan 6, 2021, at 8:22 PM, San Juan ***@***.***> wrote: remember if you are using Firefox or another browser or app set it to take the system proxy or manually configure it to 127.0.0.1:8081 or the port you have configured — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
