### ISSUE TITLE
imposible ejecutar en macOS 11.2.3

### ISSUE THREAD

**Issue by kjoe07** [rsanjuan87/PsiphonQt#8]
al ejecutar la app muestra el mensaje siguiente 
![Captura de Pantalla 2021-04-21 a la(s) 10 22 40 a m](https://user-images.githubusercontent.com/3653060/115569898-a5c16180-a28b-11eb-96aa-c5ad9280eae3.png)
trate ejecutando el extra fixToRun mismo resultado deshabilitando el gatekeeper mismo resultado

**Comment by rsanjuan87** [comment]
@kjoe07 Esto no es un bug de la app, es de la seguridad de MacOS BisSur
Valla a Preferencias/Seguridad y permita la ejecución de la app

**Comment by kjoe07** [comment]
![Captura de Pantalla 2021-04-21 a la(s) 10 57 11 a m](https://user-images.githubusercontent.com/3653060/115575256-63e6ea00-a290-11eb-908b-8e06433ee4b3.png)
pues eso pense yo y no no esta la opción en preferencias seguridad para permitir ejecutar la app

**Comment by rsanjuan87** [comment]
@kjoe07 Para solucionar necesito más detalles
Los cartelitos de MacOS no son muy descriptivos e incluso dan información errónea si usuario
Por favor ejecutar en la terminal y en el grupo de #PsiphonQt  o en el issue en Github mostrar la salida del error al ejecutar

**Comment by kjoe07** [comment]
como lo ejecuto en terminal no lo veo en el pagina de GitHub que comando uso para levantar la app

**Comment by reyespinosa1996** [comment]
Debería escribir en el grupo de soporte en Telegram. Igualmente le respondo por aquí. Con sólo escribir la ruta al ejecutable en la terminal y dar enter debería arrancar la aplicación gráfica.
-- 
 Enviado con Tutanota, el correo seguro y sin publicidad: 
 https://tutanota.com


21 de abril de 2021 19:58 por ***@***.***:

**Comment by rsanjuan87** [comment]
Alguien con MacOS BigSur en adelante podría probar el nuevo build y comentar si ya le funciona ?
https://github.com/rsanjuan87/PsiphonQt/releases/download/v1.1.2/PsiphonQt.dmg

**Comment by rsanjuan87** [comment]
Probado OK en MacOS Monterey

**Comment by kjoe07** [comment]
probado y funcionando en Monterrey listo
